CREATE TABLE [dbo].[PERSON](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[FIRST_NAME] [varchar](80) NOT NULL,
	[LAST_NAME] [varchar](80) NULL,
	[ADDRESS] [varchar](100) NOT NULL,
	[GENDER] [varchar](8) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

