CREATE TABLE USERS (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,
	USER_NAME VARCHAR(50) NOT NULL DEFAULT '0',
	PASSWORD VARCHAR(130) NOT NULL DEFAULT '0',
	FULL_NAME VARCHAR(120) NOT NULL,
	REFRESH_TOKEN VARCHAR(500) NULL DEFAULT '0',
	REFRESH_TOKEN_EXPIRY_TIME DATETIME NULL DEFAULT NULL	
)
